### ISSUE TITLE
JS errors after installing Laminas MVC skeleton

### ISSUE THREAD

**Issue by divix1988** [laminas/laminas-mvc-skeleton#7] opened 2020-02-19 22:45 UTC
### Bug Report

![image](https://user-images.githubusercontent.com/6444400/74883761-f086d700-5371-11ea-8370-4be31feb8e1a.png)

#### Summary

Some JS error appearing for fresh skeleton installation.

#### Current behavior

See image above

#### How to reproduce

install plain skeleton and open the URL.

#### Expected behavior

No errors, more fun!

**Comment by michalbundyra** [comment] 2020-02-20 07:59
Duplicate of https://github.com/laminas/laminas-developer-tools/pull/28

**Closed by michalbundyra** 2020-02-20 07:59 UTC
Labels: Duplicate
